# Generated by Django 3.2.25 on 2026-05-27 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ingestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(default='US', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('imported_by', models.CharField(default='analyst', max_length=120)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('accepted_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-imported_at',),
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP fuel/procurement'), ('utility', 'Utility electricity'), ('travel', 'Corporate travel')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('extraction_mode', models.CharField(max_length=160)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ingestion.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('source_row_id', models.CharField(blank=True, max_length=120)),
                ('payload', ingestion.models.JSONTextField()),
                ('status', models.CharField(default='accepted', max_length=20)),
                ('errors', ingestion.models.JSONTextField(blank=True, default=list)),
                ('warnings', ingestion.models.JSONTextField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
            ],
            options={
                'unique_together': {('batch', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(max_length=30)),
                ('normalized_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('normalized_unit', models.CharField(max_length=30)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('source_reference', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('suspicious_reasons', ingestion.models.JSONTextField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('edited', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingestion.facility')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.tenant')),
            ],
            options={
                'ordering': ('review_status', '-activity_date'),
            },
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ingestion.sourcesystem'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.tenant'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingestion.tenant'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='analyst', max_length=120)),
                ('action', models.CharField(max_length=80)),
                ('before', ingestion.models.JSONTextField(blank=True, null=True)),
                ('after', ingestion.models.JSONTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.normalizedactivity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'code')},
        ),
    ]
